from pandas import DataFrame, concat
from numpy import nan
from sqlalchemy import ForeignKey, create_engine, Table, MetaData, Column, Integer, String, inspect, select, BigInteger, Float, DateTime, text, BIGINT,  Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from loguru import logger
import re
Base = declarative_base()

class TorqFile(Base):
	__tablename__ = 'torqfiles'
	torqfileid =  Column('torqfileid', Integer, primary_key=True, autoincrement="auto", unique=False)
	tripid =  Column(Integer, ForeignKey('torqtrips.tripid'))
	torqfilename = Column(String(255))
	hash = Column(String(255))
	profile = Column(String(255))


class TorqTrip(Base):
	__tablename__ = 'torqtrips'
	tripid =  Column('tripid', Integer, primary_key=True, autoincrement="auto", unique=False)	
	filename = Column(String(255))
	fuelCost = Column(Float)
	fuelUsed = Column(Float)
	time = Column(Float)
	distanceWhilstConnectedToOBD = Column(Float)
	distance = Column(Float)
	profile = Column(String(255))
	tripdate = Column(DateTime, server_default=text('NOW()'))
	hash = Column(String(255))

class TorqLogEntry(Base):
	__tablename__ = 'torqlogentries'
	torqentryid =  Column('torqentryid', Integer, primary_key=True, autoincrement="auto")
	# torqlogid =  Column('torqlogid', Integer, primary_key=True, autoincrement="auto")
	tripid =  Column(Integer, ForeignKey('torqtrips.tripid'))
	torqfileid = Column(Integer, ForeignKey('torqfiles.torqfileid'))

class TorqEntry(Base):
	__tablename__ = 'torqlogs'
	id =  Column('id', Integer, primary_key=True, autoincrement="auto", unique=True)
	tripid =  Column(Integer, ForeignKey('torqtrips.tripid'))
	torqfileid = Column(Integer, ForeignKey('torqfiles.torqfileid'))
	AccelerationSensorTotalg = Column(Float, default=0)
	AccelerationSensorXaxisg = Column(Float, default=0)
	AccelerationSensorYaxisg = Column(Float, default=0)
	AccelerationSensorZaxisg = Column(Float, default=0)
	Actualenginetorque = Column(Float, default=0)
	Altitudem = Column(Float, default=0)
	AndroiddeviceBatteryLevel = Column(Float, default=0)
	Averagetripspeedwhilstmovingonlykmh = Column(Float, default=0)
	Averagetripspeedwhilststoppedormovingkmh = Column(Float, default=0)
	Bearing = Column(Float, default=0)
	COingkmAveragegkm = Column(Float, default=0)
	COingkmInstantaneousgkm = Column(Float, default=0)
	CostpermilekmInstantkm = Column(Float, default=0)
	CostpermilekmTripkm = Column(Float, default=0)
	DeviceTime = Column(String(255), server_default=text('NOW()')) # Column(String(255), default=0)
	DistancetoemptyEstimatedkm = Column(Float, default=0)
	DistancetravelledwithMILCELlitkm = Column(Float, default=0)
	EngineCoolantTemperatureF = Column(Float, default=0)
	EnginekWAtthewheelskW = Column(Float, default=0)
	EngineLoad = Column(Float, default=0)
	EngineRPMrpm = Column(Float, default=0)
	Fuelcosttripcost = Column(Float, default=0)
	Fuelflowratehourlhr = Column(Float, default=0)
	Fuelflowrateminuteccmin = Column(Float, default=0)
	Fuelpressurekpa = Column(Float, default=0)
	FuelRailPressurekpa = Column(Float, default=0)
	FuelRemainingCalculatedfromvehicleprofile = Column(Float, default=0)
	Fuelusedtripl = Column(Float, default=0)
	GPSAccuracym = Column(Float, default=0)
	GPSAltitudem = Column(Float, default=0)
	GPSBearing = Column(Float, default=0)
	GPSLatitude = Column(Float, default=0)
	GPSLongitude = Column(Float, default=0)
	GPSSatellites = Column(Float, default=0)
	GPSSpeedkmh = Column(Float, default=0)
	GPSTime = Column(String(255), server_default=text('NOW()'))
	GPSvsOBDSpeeddifferencekmh = Column(Float, default=0)
	GravityXG = Column(Float, default=0)
	GravityYG = Column(Float, default=0)
	GravityZG = Column(Float, default=0)
	HorizontalDilutionofPrecision = Column(Float, default=0)
	HorsepowerAtthewheelshp = Column(Float, default=0)
	IntakeAirTemperatureF = Column(Float, default=0)
	IntakeManifoldPressurekpa = Column(Float, default=0)
	KilometersPerLitreInstantkpl = Column(Float, default=0)
	KilometersPerLitreLongTermAveragekpl = Column(Float, default=0)
	Latitude = Column(Float, default=0)
	LitresPer100KilometerInstantl100km = Column(Float, default=0)
	LitresPer100KilometerLongTermAveragel100km = Column(Float, default=0)
	Longitude = Column(Float, default=0)
	MassAirFlowRategs = Column(Float, default=0)
	MilesPerGallonInstantmpg = Column(Float, default=0)
	MilesPerGallonLongTermAveragempg = Column(Float, default=0)
	SpeedGPSkmh = Column(Float, default=0)
	SpeedOBDkmh = Column(Float, default=0)
	Torqueftlb = Column(Float, default=0)
	TripaverageKPLkpl = Column(Float, default=0)
	TripaverageLitres100KMl100km = Column(Float, default=0)
	TripaverageMPGmpg = Column(Float, default=0)
	TripDistancekm = Column(Float, default=0)
	Tripdistancestoredinvehicleprofilekm = Column(Float, default=0)
	TripTimeSincejourneystarts = Column(Float, default=0)
	Triptimewhilstmovings = Column(Float, default=0)
	Triptimewhilststationarys = Column(Float, default=0)
	TurboBoostVacuumGaugebar = Column(Float, default=0)
	VoltageOBDAdapterV = Column(Float, default=0)
	VolumetricEfficiencyCalculated = Column(Float, default=0)

