FIELDMAPS = {
             'Acceleration Sensor(Total)(g)': 'AccelerationSensorTotalg',
             'Acceleration Sensor(X axis)(g)': 'AccelerationSensorXaxisg',
             'Acceleration Sensor(Y axis)(g)': 'AccelerationSensorYaxisg',
             'Acceleration Sensor(Z axis)(g)': 'AccelerationSensorZaxisg',
             'Actual engine % torque(%)': 'Actualenginetorque',
             'Altitude(m)': 'Altitudem',
             'Android device Battery Level(%)': 'AndroiddeviceBatteryLevel',
             'Average trip speed(whilst stopped or moving)(km/h)': 'Averagetripspeedwhilststoppedormovingkm',
             'Average trip speed(whilst moving only)(km/h)': 'Averagetripspeedwhilststoppedormovingonlykm',
             'Bearing': 'Bearing',
             'CO in g/km (Average)(g/km)': 'COaing',
             'CO‚‚ in g/km (Average)(g/km)': 'COaing',
             'CO in g/km (Instantaneous)(g/km)': 'COing',
             'CO,, in g/km (Instantaneous)(g/km)': 'COing',
             'CO‚‚ in g/km (Instantaneous)(g/km)': 'COing',
             'Cost per mile/km (Instant)($/km)': 'costpermilekminst',
             'Cost per mile/km (Trip)($/km)': 'costpermilekm',
             'Device Time': 'DeviceTime',
             'Distance to empty (Estimated)(km)': 'DistancetoemptyEstimatedkm',
             'Distance travelled with MIL/CEL lit(km)': 'DistancetravelledwithMIL',
             'Engine Coolant Temperature(°F)': 'EngineCoolantTemperatureF',
             'Engine kW (At the wheels)(kW)': 'EnginekWAtthewheelskW',
             'Engine Load(%)': 'EngineLoad',
             'Engine RPM(rpm)': 'EngineRPMrpm',
             'Fuel cost (trip)(cost)': 'Fuelcosttripcost',
             'Fuel flow rate/hour(l/hr)': 'Fuelflowratelhr',
             'Fuel flow rate/minute(cc/min)': 'Fuelflowrateccmin',
             'Fuel pressure(kpa)': 'Fuelpressurekpa',
             'Fuel Rail Pressure(kpa)': 'FuelRailPressurekpa',
             'Fuel Remaining (Calculated from vehicle profile)(%)': 'FuelRemainingCalculatedfromvehicleprofile',
             'Fuel used (trip)(l)': 'Fuelusedtripl',
             'GPS Accuracy(m)': 'GPSAccuracym',
             'GPS Altitude(m)': 'GPSAltitudem',
             'GPS Bearing(°)': 'GPSBearing',
             'GPS Latitude(°)': 'GPSLatitude',
             'GPS Longitude(°)': 'GPSLongitude',
             'GPS Satellites': 'GPSSatellites',
             'GPS Speed(km/h)': 'GPSSpeedkm',
             'GPSSpeed(km/h)': 'GPSSpeedkm',
             'GPS Time': 'GPSTime',
             'GPSTime': 'GPSTime',
             'GPS vs OBD Speed difference(km/h)': 'GPSvsOBDSpeeddifferencekm',
             'Gravity X(G)': 'GravityXG',
             'Gravity Y(G)': 'GravityYG',
             'Gravity Z(G)': 'GravityZG',
             'GravityX(G)': 'GravityXG',
             'GravityY(G)': 'GravityYG',
             'GravityZ(G)': 'GravityZG',
             'Horizontal Dilution of Precision': 'HorizontalDilutionofPrecision',
             'Horsepower (At the wheels)(hp)': 'HorsepowerAtthewheelshp',
             'Intake Air Temperature(°F)': 'IntakeAirTemperatureF',
             'Intake Manifold Pressure(kpa)': 'IntakeManifoldPressurekpa',
             'Kilometers Per Litre(Instant)(kpl)': 'KilometersPerLitreInstantkpl',
             'Kilometers Per Litre(Long Term Average)(kpl)': 'KilometersPerLitreLongTermAveragekpl',
             'Latitude': 'Latitude',
             'Litres Per 100 Kilometer(Instant)(l/100km)': 'LitresPer100KilometerInstantl',
             'Litres Per 100 Kilometer(Long Term Average)(l/100km)': 'LitresPer100KilometerLongTermAveragel',
             'Longitude': 'Longitude',
             'Mass Air Flow Rate(g/s)': 'MassAirFlowRateg',
             'Miles Per Gallon(Instant)(mpg)': 'MilesPerGallonInstantmpg',
             'Miles Per Gallon(Long Term Average)(mpg)': 'MilesPerGallonLongTermAveragempg',
             'Speed (OBD)(km/h)': 'SpeedOBDkm',
             'Speed (GPS)(km/h)': 'SpeedGPSkm',
             'Torque(ft-lb)': 'Torqueftlb',
             'Torque(ftlb)': 'Torqueftlb',
             'Trip average KPL(kpl)': 'TripaverageKPLkpl',
             'Trip average Litres/100 KM(l/100km)': 'TripaverageLitres',
             'Trip average MPG(mpg)': 'TripaverageMPGmpg',
             'Trip distance (stored in vehicle profile)(km)': 'Tripdistancestoredinvehicleprofilekm',
             'Trip Distance(km)': 'TripDistancekm',
             'Trip Time(Since journey start)(s)': 'TripTimeSincejourneystarts',
             'Trip time(whilst moving)(s)': 'Triptimewhilstmovings',
             'Trip time(whilst stationary)(s)': 'Triptimewhilststationarys',
             'Turbo Boost & Vacuum Gauge(bar)': 'TurboBoostVacuumGaugebar',
             'Voltage (OBD Adapter)(V)': 'VoltageOBDAdapterV',
             'Volumetric Efficiency (Calculated)(%)': 'VolumetricEfficiencyCalculated',
             'Unnamed: 0': 'unnamed0',
            'AccelerationSensorTotalg':'AccelerationSensorTotalg',
            'AccelerationSensorXaxisg':'AccelerationSensorXaxisg',
            'AccelerationSensorYaxisg':'AccelerationSensorYaxisg',
            'AccelerationSensorZaxisg':'AccelerationSensorZaxisg',
            'Actualenginetorque':'Actualenginetorque',
            'Altitudem':'Altitudem',
            'AndroiddeviceBatteryLevel':'AndroiddeviceBatteryLevel',
            'Averagetripspeedwhilststoppedormovingkm':'Averagetripspeedwhilststoppedormovingkm',
            'Averagetripspeedwhilststoppedormovingonlykm':'Averagetripspeedwhilststoppedormovingonlykm',
            'Bearing':'Bearing',
            'COaing':'COaing',
            'COaing':'COaing',
            'COing':'COing',
            'COing':'COing',
            'COing':'COing',
            'costpermilekminst':'costpermilekminst',
            'costpermilekm':'costpermilekm',
            'DeviceTime':'DeviceTime',
            'DistancetoemptyEstimatedkm':'DistancetoemptyEstimatedkm',
            'DistancetravelledwithMIL':'DistancetravelledwithMIL',
            'EngineCoolantTemperatureF':'EngineCoolantTemperatureF',
            'EnginekWAtthewheelskW':'EnginekWAtthewheelskW',
            'EngineLoad':'EngineLoad',
            'EngineRPMrpm':'EngineRPMrpm',
            'Fuelcosttripcost':'Fuelcosttripcost',
            'Fuelflowratelhr':'Fuelflowratelhr',
            'Fuelflowrateccmin':'Fuelflowrateccmin',
            'Fuelpressurekpa':'Fuelpressurekpa',
            'FuelRailPressurekpa':'FuelRailPressurekpa',
            'FuelRemainingCalculatedfromvehicleprofile':'FuelRemainingCalculatedfromvehicleprofile',
            'Fuelusedtripl':'Fuelusedtripl',
            'GPSAccuracym':'GPSAccuracym',
            'GPSAltitudem':'GPSAltitudem',
            'GPSBearing':'GPSBearing',
            'GPSLatitude':'GPSLatitude',
            'GPSLongitude':'GPSLongitude',
            'GPSSatellites':'GPSSatellites',
            'GPSSpeedkm':'GPSSpeedkm',
            'GPSTime':'GPSTime',
            'GPSTime':'GPSTime',
            'GPSvsOBDSpeeddifferencekm':'GPSvsOBDSpeeddifferencekm',
            'GravityXG':'GravityXG',
            'GravityYG':'GravityYG',
            'GravityZG':'GravityZG',
            'HorizontalDilutionofPrecision':'HorizontalDilutionofPrecision',
            'HorsepowerAtthewheelshp':'HorsepowerAtthewheelshp',
            'IntakeAirTemperatureF':'IntakeAirTemperatureF',
            'IntakeManifoldPressurekpa':'IntakeManifoldPressurekpa',
            'KilometersPerLitreInstantkpl':'KilometersPerLitreInstantkpl',
            'KilometersPerLitreLongTermAveragekpl':'KilometersPerLitreLongTermAveragekpl',
            'Latitude':'Latitude',
            'LitresPer100KilometerInstantl':'LitresPer100KilometerInstantl',
            'LitresPer100KilometerLongTermAveragel':'LitresPer100KilometerLongTermAveragel',
            'Longitude':'Longitude',
            'MassAirFlowRateg':'MassAirFlowRateg',
            'MilesPerGallonInstantmpg':'MilesPerGallonInstantmpg',
            'MilesPerGallonLongTermAveragempg':'MilesPerGallonLongTermAveragempg',
            'SpeedOBDkm':'SpeedOBDkm',
            'SpeedGPSkm':'SpeedGPSkm',
            'Torqueftlb':'Torqueftlb',
            'Torqueftlb':'Torqueftlb',
            'TripaverageKPLkpl':'TripaverageKPLkpl',
            'TripaverageLitres':'TripaverageLitres',
            'TripaverageMPGmpg':'TripaverageMPGmpg',
            'Tripdistancestoredinvehicleprofilekm':'Tripdistancestoredinvehicleprofilekm',
            'TripDistancekm':'TripDistancekm',
            'TripTimeSincejourneystarts':'TripTimeSincejourneystarts',
            'Triptimewhilstmovings':'Triptimewhilstmovings',
            'Triptimewhilststationarys':'Triptimewhilststationarys',
            'TurboBoostVacuumGaugebar':'TurboBoostVacuumGaugebar',
            'VoltageOBDAdapterV':'VoltageOBDAdapterV',
            'VolumetricEfficiencyCalculated':'VolumetricEfficiencyCalculated',
        'AccelerationSensor(Total)(g)':'AccelerationSensorTotalg',
        'AccelerationSensor(Xaxis)(g)':'AccelerationSensorXaxisg',
        'AccelerationSensor(Yaxis)(g)':'AccelerationSensorYaxisg',
        'AccelerationSensor(Zaxis)(g)':'AccelerationSensorZaxisg',
        'Actualengine%torque(%)':'Actualenginetorque',
        'Altitude(m)':'Altitudem',
        'AndroiddeviceBatteryLevel(%)':'AndroiddeviceBatteryLevel',
        'Averagetripspeed(whilststoppedormoving)(km/h)':'Averagetripspeedwhilststoppedormovingkm',
        'Averagetripspeed(whilstmovingonly)(km/h)':'Averagetripspeedwhilststoppedormovingonlykm',
        'Bearing':'Bearing',
        'COing/km(Average)(g/km)':'COaing',
        'CO‚‚ing/km(Average)(g/km)':'COaing',
        'COing/km(Instantaneous)(g/km)':'COing',
        'CO,,ing/km(Instantaneous)(g/km)':'COing',
        'CO‚‚ing/km(Instantaneous)(g/km)':'COing',
        'Costpermile/km(Instant)($/km)':'costpermilekminst',
        'Costpermile/km(Trip)($/km)':'costpermilekm',
        'DeviceTime':'DeviceTime',
        'Distancetoempty(Estimated)(km)':'DistancetoemptyEstimatedkm',
        'DistancetravelledwithMIL/CELlit(km)':'DistancetravelledwithMIL',
        'EngineCoolantTemperature(°F)':'EngineCoolantTemperatureF',
        'EnginekW(Atthewheels)(kW)':'EnginekWAtthewheelskW',
        'EngineLoad(%)':'EngineLoad',
        'EngineRPM(rpm)':'EngineRPMrpm',
        'Fuelcost(trip)(cost)':'Fuelcosttripcost',
        'Fuelflowrate/hour(l/hr)':'Fuelflowratelhr',
        'Fuelflowrate/minute(cc/min)':'Fuelflowrateccmin',
        'Fuelpressure(kpa)':'Fuelpressurekpa',
        'FuelRailPressure(kpa)':'FuelRailPressurekpa',
        'FuelRemaining(Calculatedfromvehicleprofile)(%)':'FuelRemainingCalculatedfromvehicleprofile',
        'Fuelused(trip)(l)':'Fuelusedtripl',
        'GPSAccuracy(m)':'GPSAccuracym',
        'GPSAltitude(m)':'GPSAltitudem',
        'GPSBearing(°)':'GPSBearing',
        'GPSLatitude(°)':'GPSLatitude',
        'GPSLongitude(°)':'GPSLongitude',
        'GPSSatellites':'GPSSatellites',
        'GPSSpeed(km/h)':'GPSSpeedkm',
        'GPSSpeed(km/h)':'GPSSpeedkm',
        'GPSTime':'GPSTime',
        'GPSTime':'GPSTime',
        'GPSvsOBDSpeeddifference(km/h)':'GPSvsOBDSpeeddifferencekm',
        'GravityX(G)':'GravityXG',
        'GravityY(G)':'GravityYG',
        'GravityZ(G)':'GravityZG',
        'GravityX(G)':'GravityXG',
        'GravityY(G)':'GravityYG',
        'GravityZ(G)':'GravityZG',
        'HorizontalDilutionofPrecision':'HorizontalDilutionofPrecision',
        'Horsepower(Atthewheels)(hp)':'HorsepowerAtthewheelshp',
        'IntakeAirTemperature(°F)':'IntakeAirTemperatureF',
        'IntakeManifoldPressure(kpa)':'IntakeManifoldPressurekpa',
        'KilometersPerLitre(Instant)(kpl)':'KilometersPerLitreInstantkpl',
        'KilometersPerLitre(LongTermAverage)(kpl)':'KilometersPerLitreLongTermAveragekpl',
        'Latitude':'Latitude',
        'LitresPer100Kilometer(Instant)(l/100km)':'LitresPer100KilometerInstantl',
        'LitresPer100Kilometer(LongTermAverage)(l/100km)':'LitresPer100KilometerLongTermAveragel',
        'Longitude':'Longitude',
        'MassAirFlowRate(g/s)':'MassAirFlowRateg',
        'MilesPerGallon(Instant)(mpg)':'MilesPerGallonInstantmpg',
        'MilesPerGallon(LongTermAverage)(mpg)':'MilesPerGallonLongTermAveragempg',
        'Speed(OBD)(km/h)':'SpeedOBDkm',
        'Speed(GPS)(km/h)':'SpeedGPSkm',
        'Torque(ft-lb)':'Torqueftlb',
        'Torque(ftlb)':'Torqueftlb',
        'TripaverageKPL(kpl)':'TripaverageKPLkpl',
        'TripaverageLitres/100KM(l/100km)':'TripaverageLitres',
        'TripaverageMPG(mpg)':'TripaverageMPGmpg',
        'Tripdistance(storedinvehicleprofile)(km)':'Tripdistancestoredinvehicleprofilekm',
        'TripDistance(km)':'TripDistancekm',
        'TripTime(Sincejourneystart)(s)':'TripTimeSincejourneystarts',
        'Triptime(whilstmoving)(s)':'Triptimewhilstmovings',
        'Triptime(whilststationary)(s)':'Triptimewhilststationarys',
        'TurboBoost&VacuumGauge(bar)':'TurboBoostVacuumGaugebar',
        'Voltage(OBDAdapter)(V)':'VoltageOBDAdapterV',
        'VolumetricEfficiency(Calculated)(%)':'VolumetricEfficiencyCalculated',

             }
