FIELDMAPS = {'Acceleration Sensor(Total)(g)': 'AccelerationSensorTotalg',
             'Acceleration Sensor(X axis)(g)': 'AccelerationSensorXaxisg',
             'Acceleration Sensor(Y axis)(g)': 'AccelerationSensorYaxisg',
             'Acceleration Sensor(Z axis)(g)': 'AccelerationSensorZaxisg',
             'Actual engine % torque(%)': 'Actualenginetorque',
             'Altitude(m)': 'Altitudem',
             'Android device Battery Level(%)': 'AndroiddeviceBatteryLevel',
             'Average trip speed(whilst stopped or moving)(km/h)': 'Averagetripspeedwhilststoppedormovingkm',
             'Average trip speed(whilst moving only)(km/h)': 'Averagetripspeedwhilststoppedormovingonlykm',
             'Bearing': 'Bearing',
             'CO in g/km (Average)(g/km)': 'COaing',
             'CO‚‚ in g/km (Average)(g/km)': 'COaing',
             'CO in g/km (Instantaneous)(g/km)': 'COing',
             'CO,, in g/km (Instantaneous)(g/km)': 'COing',
             'CO‚‚ in g/km (Instantaneous)(g/km)': 'COing',
             'Cost per mile/km (Instant)($/km)': 'costpermilekminst',
             'Cost per mile/km (Trip)($/km)': 'costpermilekm',
             'Device Time': 'DeviceTime',
             'Distance to empty (Estimated)(km)': 'DistancetoemptyEstimatedkm',
             'Distance travelled with MIL/CEL lit(km)': 'DistancetravelledwithMIL',
             'Engine Coolant Temperature(°F)': 'EngineCoolantTemperatureF',
             'Engine kW (At the wheels)(kW)': 'EnginekWAtthewheelskW',
             'Engine Load(%)': 'EngineLoad',
             'Engine RPM(rpm)': 'EngineRPMrpm',
             'Fuel cost (trip)(cost)': 'Fuelcosttripcost',
             'Fuel flow rate/hour(l/hr)': 'Fuelflowratelhr',
             'Fuel flow rate/minute(cc/min)': 'Fuelflowrateccmin',
             'Fuel pressure(kpa)': 'Fuelpressurekpa',
             'Fuel Rail Pressure(kpa)': 'FuelRailPressurekpa',
             'Fuel Remaining (Calculated from vehicle profile)(%)': 'FuelRemainingCalculatedfromvehicleprofile',
             'Fuel used (trip)(l)': 'Fuelusedtripl',
             'GPS Accuracy(m)': 'GPSAccuracym',
             'GPS Altitude(m)': 'GPSAltitudem',
             'GPS Bearing(°)': 'GPSBearing',
             'GPS Latitude(°)': 'GPSLatitude',
             'GPS Longitude(°)': 'GPSLongitude',
             'GPS Satellites': 'GPSSatellites',
             'GPS Speed(km/h)': 'GPSSpeedkm',
             'GPS Time': 'GPSTime',
             'GPS vs OBD Speed difference(km/h)': 'GPSvsOBDSpeeddifferencekm',
             'Gravity X(G)': 'GravityXG',
             'Gravity Y(G)': 'GravityYG',
             'Gravity Z(G)': 'GravityZG',
             'Horizontal Dilution of Precision': 'HorizontalDilutionofPrecision',
             'Horsepower (At the wheels)(hp)': 'HorsepowerAtthewheelshp',
             'Intake Air Temperature(°F)': 'IntakeAirTemperatureF',
             'Intake Manifold Pressure(kpa)': 'IntakeManifoldPressurekpa',
             'Kilometers Per Litre(Instant)(kpl)': 'KilometersPerLitreInstantkpl',
             'Kilometers Per Litre(Long Term Average)(kpl)': 'KilometersPerLitreLongTermAveragekpl',
             'Latitude': 'Latitude',
             'Litres Per 100 Kilometer(Instant)(l/100km)': 'LitresPer100KilometerInstantl',
             'Litres Per 100 Kilometer(Long Term Average)(l/100km)': 'LitresPer100KilometerLongTermAveragel',
             'Longitude': 'Longitude',
             'Mass Air Flow Rate(g/s)': 'MassAirFlowRateg',
             'Miles Per Gallon(Instant)(mpg)': 'MilesPerGallonInstantmpg',
             'Miles Per Gallon(Long Term Average)(mpg)': 'MilesPerGallonLongTermAveragempg',
             'Speed (OBD)(km/h)': 'SpeedOBDkm',
             'Speed (GPS)(km/h)': 'SpeedGPSkm',
             'Torque(ft-lb)': 'Torqueftlb',
             'Torque(ftlb)': 'Torqueftlb',
             'Trip average KPL(kpl)': 'TripaverageKPLkpl',
             'Trip average Litres/100 KM(l/100km)': 'TripaverageLitres',
             'Trip average MPG(mpg)': 'TripaverageMPGmpg',
             'Trip distance (stored in vehicle profile)(km)': 'Tripdistancestoredinvehicleprofilekm',
             'Trip Distance(km)': 'TripDistancekm',
             'Trip Time(Since journey start)(s)': 'TripTimeSincejourneystarts',
             'Trip time(whilst moving)(s)': 'Triptimewhilstmovings',
             'Trip time(whilst stationary)(s)': 'Triptimewhilststationarys',
             'Turbo Boost & Vacuum Gauge(bar)': 'TurboBoostVacuumGaugebar',
             'Voltage (OBD Adapter)(V)': 'VoltageOBDAdapterV',
             'Volumetric Efficiency (Calculated)(%)': 'VolumetricEfficiencyCalculated'}
