import polars as pl

ncc = {
	'Barometric pressure (from vehicle)(kpa)' : 'barometricpressurefromvehiclekpa',
	'Cost per mile/km (Instant)($/km)': 'costpermilekminstantkm',
	'Cost per mile/km (Trip)($/km)' :  'costpermilekmtripkm',
	'Fuel pressure(kpa)':'fuelpressurekpa',
	"Torque(Nm)": "torquefnm",
    "Acceleration Sensor(Total)(g)": "accelerationsensortotalg",
    "Acceleration Sensor(X axis)(g)": "accelerationsensorxaxisg",
    "Acceleration Sensor(Y axis)(g)": "accelerationsensoryaxisg",
    "Acceleration Sensor(Z axis)(g)": "accelerationsensorzaxisg",
    "Actual engine % torque(%)": "actualenginetorque",
    "Air Fuel Ratio(Measured)(:1)": "airfuelrationmeasure",
    "Altitude": "altitudem",
    "Altitude(m)": "altitudem",
    "Ambient air temp(°C)": "ambientairtempc",
    "Ambient air temp(°F)": "ambientairtempf",
    "Android device Battery Level(%)": "androiddevicebatterylevel",
    "Average trip speed(whilst moving only)(km/h)": "averagetripspeedwhilstmovingonlykmh",
    "Average trip speed(whilst stopped or moving)(km/h)": "averagetripspeedwhilststoppedormovingkmh",
    "Barometric pressure (from vehicle)(psi)": "barometricpressurefromvpsi",
    "Bearing": "bearing",
    "CO₂ in g/km (Average)(g/km)": "coingkmaveragegkm",
    "CO₂ in g/km (Instantaneous)(g/km)": "coingkminstantaneousgkm",
    "Device Time": "devicetime",
    "Distance to empty (Estimated)(km)": "distancetoemptyestimatedkm",
    "Distance travelled with MIL/CEL lit(km)": "distancetravelledwithmilcellitkm",
    "Engine Coolant Temperature(°C)": "enginecoolanttemperaturec",
    "Engine Coolant Temperature(°F)": "enginecoolanttemperaturef",
    "Engine kW (At the wheels)(kW)": "enginekwatthewheelskw",
    "Engine Load(%)": "engineload",
    "Engine RPM(rpm)": "enginerpmrpm",
    "Fuel cost (trip)(cost)": "fuelcosttripcost",
    "Fuel flow rate/hour(l/hr)": "fuelflowratehourlhr",
    "Fuel flow rate/minute(cc/min)": "fuelflowrateminuteccmin",
    "Fuel Rail Pressure(kpa)": "fuelrailpressurekpa",
    "Fuel Rail Pressure(psi)": "fuelrailpressurepsi",
    "Fuel Remaining (Calculated from vehicle profile)(%)": "fuelremainingcalculatedfromvehicleprofile",
    "Fuel used (trip)(l)": "fuelusedtripl",
    "G(calibrated)": "gcalibrated",
    "G(x)": "gravityxg",
    "G(y)": "gravityyg",
    "G(z)": "gravityzg",
    "GPS Accuracy(m)": "gpsaccuracym",
    "GPS Altitude(m)": "gpsaltitudem",
    "GPS Bearing(°)": "gpsbearing",
    "GPS Latitude(°)": "gpslatitude",
    "GPS Longitude(°)": "gpslongitude",
    "GPS Satellites": "gpssatellites",
    "GPS Speed (Meters/second)": "gpsspeedmeterssecond",
    "GPS Speed(km/h)": "gpsspeedkmh",
    "GPS Time": "gpstime",
    "GPS vs OBD Speed difference(km/h)": "gpsvsobdspeeddifferencekmh",
    "Gravity X(G)": "gravityxg",
    "Gravity Y(G)": "gravityyg",
    "Gravity Z(G)": "gravityzg",
    "Horizontal Dilution of Precision": "horizontaldilutionofprecision",
    "Horsepower (At the wheels)(hp)": "horsepoweratthewheelshp",
    "Intake Air Temperature(°C)": "intakeairtemperaturec",
    "Intake Air Temperature(°F)": "intakeairtemperaturef",
    "Intake Manifold Pressure(kpa)": "intakemanifoldpressurekpa",
    "Intake Manifold Pressure(psi)": "intakemanifoldpressurepsi",
    "Kilometers Per Litre(Instant)(kpl)": "kilometersperlitreinstantkpl",
    "Kilometers Per Litre(Long Term Average)(kpl)": "kilometersperlitrelongtermaveragekpl",
    "Latitude": "latitude",
    "Litres Per 100 Kilometer(Instant)(l/100km)": "litresper100kilometerinstantl100km",
    "Litres Per 100 Kilometer(Long Term Average)(l/100km)": "litresper100kilometerlongtermaveragel100km",
    "Longitude": "longitude",
    "Mass Air Flow Rate(g/s)": "massairflowrategs",
    "Miles Per Gallon(Instant)(mpg)": "milespergalloninstantmpg",
    "Miles Per Gallon(Long Term Average)(mpg)": "milespergallonlongtermaveragempg",
    "O2 Bank 1 Sensor 1 Wide Range Equivalence Ratio(λ)": "o2bank1sensor1widerangeequivalenceratio",
    "O2 Bank 1 Sensor 1 Wide Range Voltage(V)": "o2bank1sensor1widerangevoltagev",
    "O2 Sensor1 Wide Range Current(mA)": "o2sensor1widerangecurrentma",
    "Positive Kinetic Energy (PKE)(km/hr²)": "positivekineticenergypkekmhr",
    "Speed (GPS)(km/h)": "speedgpskmh",
    "Speed (OBD)(km/h)": "speedobdkmh",
    "Throttle Position(Manifold)(%)": "throttlepositionmanifold",
    "Torque(ft-lb)": "torqueftlb",
    "Trip average KPL(kpl)": "tripaveragekplkpl",
    "Trip average Litres/100 KM(l/100km)": "tripaveragelitres100kml100km",
    "Trip average MPG(mpg)": "tripaveragempgmpg",
    "Trip distance (stored in vehicle profile)(km)": "tripdistancestoredinvehicleprofilekm",
    "Trip Distance(km)": "tripdistancekm",
    "Trip Time(Since journey start)(s)": "triptimesincejourneystarts",
    "Trip time(whilst moving)(s)": "triptimewhilstmovings",
    "Trip time(whilst stationary)(s)": "triptimewhilststationarys",
    "Turbo Boost & Vacuum Gauge(bar)": "turboboostvacuumgaugebar",
    "Turbo Boost & Vacuum Gauge(psi)": "turboboostvacuumgaugepsi",
    "Voltage (Control Module)(V)": "voltagecontrolmodulev",
    "Voltage (OBD Adapter)(V)": "voltageobdadapterv",
    "Volumetric Efficiency (Calculated)(%)": "volumetricefficiencycalculated",
}

schema_pl_org = {
    "GPS Time": pl.Datetime,
    "Device Time": pl.Datetime,
    "Longitude": pl.Float32,
    "Latitude": pl.Float32,
    "GPS Speed(km/h)": pl.Float32,
    "Horizontal Dilution of Precision": pl.Float32,
    "Altitude(m)": pl.Float32,
    "Bearing": pl.Float32,
    "Gravity X(G)": pl.Float32,
    "Gravity Y(G)": pl.Float32,
    "Gravity Z(G)": pl.Float32,
    "Acceleration Sensor(Total)(g)": pl.Float32,
    "Acceleration Sensor(X axis)(g)": pl.Float32,
    "Acceleration Sensor(Y axis)(g)": pl.Float32,
    "Acceleration Sensor(Z axis)(g)": pl.Float32,
    "Actual engine % torque(%)": pl.Float32,
    "Android device Battery Level(%)": pl.Float32,
    "Average trip speed(whilst moving only)(km/h)": pl.Float32,
    "Average trip speed(whilst stopped or moving)(km/h)": pl.Float32,
    "CO₂ in g/km (Average)(g/km)": pl.Float32,
    "CO₂ in g/km (Instantaneous)(g/km)": pl.Float32,
    "Distance to empty (Estimated)(km)": pl.Float32,
    "Distance travelled with MIL/CEL lit(km)": pl.Float32,
    "Engine Coolant Temperature(°F)": pl.Float32,
    "Engine kW (At the wheels)(kW)": pl.Float32,
    "Engine Load(%)": pl.Float32,
    "Engine RPM(rpm)": pl.Float32,
    "Fuel cost (trip)(cost)": pl.Float32,
    "Fuel flow rate/hour(l/hr)": pl.Float32,
    "Fuel flow rate/minute(cc/min)": pl.Float32,
    "Fuel Rail Pressure(kpa)": pl.Float32,
    "Fuel Remaining (Calculated from vehicle profile)(%)": pl.Float32,
    "Fuel used (trip)(l)": pl.Float32,
    "GPS Accuracy(m)": pl.Float32,
    "GPS Altitude(m)": pl.Float32,
    "GPS Bearing(°)": pl.Float32,
    "GPS Latitude(°)": pl.Float32,
    "GPS Longitude(°)": pl.Float32,
    "GPS Satellites": pl.Float32,
    "GPS vs OBD Speed difference(km/h)": pl.Float32,
    "Horsepower (At the wheels)(hp)": pl.Float32,
    "Intake Air Temperature(°F)": pl.Float32,
    "Intake Manifold Pressure(kpa)": pl.Float32,
    "Kilometers Per Litre(Instant)(kpl)": pl.Float32,
    "Kilometers Per Litre(Long Term Average)(kpl)": pl.Float32,
    "Litres Per 100 Kilometer(Instant)(l/100km)": pl.Float32,
    "Litres Per 100 Kilometer(Long Term Average)(l/100km)": pl.Float32,
    "Mass Air Flow Rate(g/s)": pl.Float32,
    "Miles Per Gallon(Instant)(mpg)": pl.Float32,
    "Miles Per Gallon(Long Term Average)(mpg)": pl.Float32,
    "Speed (GPS)(km/h)": pl.Float32,
    "Speed (OBD)(km/h)": pl.Float32,
    "Torque(ft-lb)": pl.Float32,
    "Trip average KPL(kpl)": pl.Float32,
    "Trip average Litres/100 KM(l/100km)": pl.Float32,
    "Trip average MPG(mpg)": pl.Float32,
    "Trip Distance(km)": pl.Float32,
    "Trip distance (stored in vehicle profile)(km)": pl.Float32,
    "Trip Time(Since journey start)(s)": pl.Float32,
    "Trip time(whilst moving)(s)": pl.Float32,
    "Trip time(whilst stationary)(s)": pl.Float32,
    "Turbo Boost & Vacuum Gauge(bar)": pl.Float32,
    "Voltage (OBD Adapter)(V)": pl.Float32,
    "Volumetric Efficiency (Calculated)(%)": pl.Float32,
    "TripDistancekm": pl.Float32,
}

schema_pl_clean_names = {
    "GPSTime": pl.Datetime,
    "DeviceTime": pl.Datetime,
    "Longitude": pl.Float32,
    "Latitude": pl.Float32,
    "GPSSpeedkmh": pl.Float32,
    "HorizontalDilutionofPrecision": pl.Float32,
    "Altitudem": pl.Float32,
    "Bearing": pl.Float32,
    "GravityXG": pl.Float32,
    "GravityYG": pl.Float32,
    "GravityZG": pl.Float32,
    "AccelerationSensorTotalg": pl.Float32,
    "AccelerationSensorXaxisg": pl.Float32,
    "AccelerationSensorYaxisg": pl.Float32,
    "AccelerationSensorZaxisg": pl.Float32,
    "Actualenginetorque": pl.Float32,
    "AndroiddeviceBatteryLevel": pl.Float32,
    "Averagetripspeedwhilstmovingonlykmh": pl.Float32,
    "Averagetripspeedwhilststoppedormovingkmh": pl.Float32,
    "COingkmAveragegkm": pl.Float32,
    "COingkmInstantaneousgkm": pl.Float32,
    "DistancetoemptyEstimatedkm": pl.Float32,
    "DistancetravelledwithMILCELlitkm": pl.Float32,
    "EngineCoolantTemperatureF": pl.Float32,
    "EnginekWAtthewheelskW": pl.Float32,
    "EngineLoad": pl.Float32,
    "EngineRPMrpm": pl.Float32,
    "Fuelcosttripcost": pl.Float32,
    "Fuelflowratehourlhr": pl.Float32,
    "Fuelflowrateminuteccmin": pl.Float32,
    "FuelRailPressurekpa": pl.Float32,
    "FuelRemainingCalculatedfromvehicleprofile": pl.Float32,
    "Fuelusedtripl": pl.Float32,
    "GPSAccuracym": pl.Float32,
    "GPSAltitudem": pl.Float32,
    "GPSBearing": pl.Float32,
    "GPSLatitude": pl.Float32,
    "GPSLongitude": pl.Float32,
    "GPSSatellites": pl.Float32,
    "GPSvsOBDSpeeddifferencekmh": pl.Float32,
    "HorsepowerAtthewheelshp": pl.Float32,
    "IntakeAirTemperatureF": pl.Float32,
    "IntakeManifoldPressurekpa": pl.Float32,
    "KilometersPerLitreInstantkpl": pl.Float32,
    "KilometersPerLitreLongTermAveragekpl": pl.Float32,
    "LitresPer100KilometerInstantl100km": pl.Float32,
    "LitresPer100KilometerLongTermAveragel100km": pl.Float32,
    "MassAirFlowRategs": pl.Float32,
    "MilesPerGallonInstantmpg": pl.Float32,
    "MilesPerGallonLongTermAveragempg": pl.Float32,
    "SpeedGPSkmh": pl.Float32,
    "SpeedOBDkmh": pl.Float32,
    "Torqueftlb": pl.Float32,
    "TripaverageKPLkpl": pl.Float32,
    "TripaverageLitres100KMl100km": pl.Float32,
    "TripaverageMPGmpg": pl.Float32,
    "TripDistancekm": pl.Float32,
    "Tripdistancestoredinvehicleprofilekm": pl.Float32,
    "TripTimeSincejourneystarts": pl.Float32,
    "Triptimewhilstmovings": pl.Float32,
    "Triptimewhilststationarys": pl.Float32,
    "TurboBoostVacuumGaugebar": pl.Float32,
    "VoltageOBDAdapterV": pl.Float32,
    "VolumetricEfficiencyCalculated": pl.Float32,
}

schema_pl_clean_names = {
    "GPSTime": pl.Datetime,
    "DeviceTime": pl.Datetime,
    "Longitude": pl.Float32,
    "Latitude": pl.Float32,
    "GPSSpeedkmh": pl.Float32,
    "HorizontalDilutionofPrecision": pl.Float32,
    "Altitudem": pl.Float32,
    "Bearing": pl.Float32,
    "GravityXG": pl.Float32,
    "GravityYG": pl.Float32,
    "GravityZG": pl.Float32,
    "AccelerationSensorTotalg": pl.Float32,
    "AccelerationSensorXaxisg": pl.Float32,
    "AccelerationSensorYaxisg": pl.Float32,
    "AccelerationSensorZaxisg": pl.Float32,
    "Actualenginetorque": pl.Float32,
    "AndroiddeviceBatteryLevel": pl.Float32,
    "Averagetripspeedwhilstmovingonlykmh": pl.Float32,
    "Averagetripspeedwhilststoppedormovingkmh": pl.Float32,
    "COingkmAveragegkm": pl.Float32,
    "COingkmInstantaneousgkm": pl.Float32,
    "DistancetoemptyEstimatedkm": pl.Float32,
    "DistancetravelledwithMILCELlitkm": pl.Float32,
    "EngineCoolantTemperatureF": pl.Float32,
    "EnginekWAtthewheelskW": pl.Float32,
    "EngineLoad": pl.Float32,
    "EngineRPMrpm": pl.Float32,
    "Fuelcosttripcost": pl.Float32,
    "Fuelflowratehourlhr": pl.Float32,
    "Fuelflowrateminuteccmin": pl.Float32,
    "FuelRailPressurekpa": pl.Float32,
    "FuelRemainingCalculatedfromvehicleprofile": pl.Float32,
    "Fuelusedtripl": pl.Float32,
    "GPSAccuracym": pl.Float32,
    "GPSAltitudem": pl.Float32,
    "GPSBearing": pl.Float32,
    "GPSLatitude": pl.Float32,
    "GPSLongitude": pl.Float32,
    "GPSSatellites": pl.Float32,
    "GPSvsOBDSpeeddifferencekmh": pl.Float32,
    "HorsepowerAtthewheelshp": pl.Float32,
    "IntakeAirTemperatureF": pl.Float32,
    "IntakeManifoldPressurekpa": pl.Float32,
    "KilometersPerLitreInstantkpl": pl.Float32,
    "KilometersPerLitreLongTermAveragekpl": pl.Float32,
    "LitresPer100KilometerInstantl100km": pl.Float32,
    "LitresPer100KilometerLongTermAveragel100km": pl.Float32,
    "MassAirFlowRategs": pl.Float32,
    "MilesPerGallonInstantmpg": pl.Float32,
    "MilesPerGallonLongTermAveragempg": pl.Float32,
    "SpeedGPSkmh": pl.Float32,
    "SpeedOBDkmh": pl.Float32,
    "Torqueftlb": pl.Float32,
    "TripaverageKPLkpl": pl.Float32,
    "TripaverageLitres100KMl100km": pl.Float32,
    "TripaverageMPGmpg": pl.Float32,
    "TripDistancekm": pl.Float32,
    "Tripdistancestoredinvehicleprofilekm": pl.Float32,
    "TripTimeSincejourneystarts": pl.Float32,
    "Triptimewhilstmovings": pl.Float32,
    "Triptimewhilststationarys": pl.Float32,
    "TurboBoostVacuumGaugebar": pl.Float32,
    "VoltageOBDAdapterV": pl.Float32,
    "VolumetricEfficiencyCalculated": pl.Float32,
}

schema_pl_clean_names_lowercase = {
    "gpstime": pl.Datetime,
    "devicetime": pl.Datetime,
    "longitude": pl.Float32,
    "latitude": pl.Float32,
    "gpsspeedkmh": pl.Float32,
    "horizontaldilutionofprecision": pl.Float32,
    "altitudem": pl.Float32,
    "bearing": pl.Float32,
    "gravityxg": pl.Float32,
    "gravityyg": pl.Float32,
    "gravityzg": pl.Float32,
    "accelerationsensortotalg": pl.Float32,
    "accelerationsensorxaxisg": pl.Float32,
    "accelerationsensoryaxisg": pl.Float32,
    "accelerationsensorzaxisg": pl.Float32,
    "actualenginetorque": pl.Float32,
    "androiddevicebatterylevel": pl.Float32,
    "averagetripspeedwhilstmovingonlykmh": pl.Float32,
    "averagetripspeedwhilststoppedormovingkmh": pl.Float32,
    "coingkmaveragegkm": pl.Float32,
    "coingkminstantaneousgkm": pl.Float32,
    "distancetoemptyestimatedkm": pl.Float32,
    "distancetravelledwithmilcellitkm": pl.Float32,
    "enginecoolanttemperaturef": pl.Float32,
    "enginekwatthewheelskw": pl.Float32,
    "engineload": pl.Float32,
    "enginerpmrpm": pl.Float32,
    "fuelcosttripcost": pl.Float32,
    "fuelflowratehourlhr": pl.Float32,
    "fuelflowrateminuteccmin": pl.Float32,
    "fuelrailpressurekpa": pl.Float32,
    "fuelremainingcalculatedfromvehicleprofile": pl.Float32,
    "fuelusedtripl": pl.Float32,
    "gpsaccuracym": pl.Float32,
    "gpsaltitudem": pl.Float32,
    "gpsbearing": pl.Float32,
    "gpslatitude": pl.Float32,
    "gpslongitude": pl.Float32,
    "gpssatellites": pl.Float32,
    "gpsvsobdspeeddifferencekmh": pl.Float32,
    "horsepoweratthewheelshp": pl.Float32,
    "intakeairtemperaturef": pl.Float32,
    "intakemanifoldpressurekpa": pl.Float32,
    "kilometersperlitreinstantkpl": pl.Float32,
    "kilometersperlitrelongtermaveragekpl": pl.Float32,
    "litresper100kilometerinstantl100km": pl.Float32,
    "litresper100kilometerlongtermaveragel100km": pl.Float32,
    "massairflowrategs": pl.Float32,
    "milespergalloninstantmpg": pl.Float32,
    "milespergallonlongtermaveragempg": pl.Float32,
    "speedgpskmh": pl.Float32,
    "speedobdkmh": pl.Float32,
    "torqueftlb": pl.Float32,
    "tripaveragekplkpl": pl.Float32,
    "tripaveragelitres100kml100km": pl.Float32,
    "tripaveragempgmpg": pl.Float32,
    "tripdistancekm": pl.Float32,
    "tripdistancestoredinvehicleprofilekm": pl.Float32,
    "triptimesincejourneystarts": pl.Float32,
    "triptimewhilstmovings": pl.Float32,
    "triptimewhilststationarys": pl.Float32,
    "turboboostvacuumgaugebar": pl.Float32,
    "voltageobdadapterv": pl.Float32,
    "volumetricefficiencycalculated": pl.Float32,
}

if __name__ == '__main__':
	pass
