mysql_cmds = {
'createfiles' : """
					create table if not exists torqfiles
					(
						id int primary key not null auto_increment,
						csvfilename  varchar(255),
						csvhash varchar(255),
						csvfilefixed varchar(255),
						fixedhash varchar(255)
					);
 """,
'createlogs' : """
				create table if not exists torqlogs(
					id int primary key not null auto_increment,
					tripid int not null,
					gpstime timestamp default current_timestamp,
					devicetime timestamp default current_timestamp,
					longitude double default 0,
					latitude double default 0,
					gpsspeedkmh double default 0,
					horizontaldilutionofprecision double default 0,
					altitudem double default 0,
					bearing double default 0,
					gravityxg double default 0,
					gravityyg double default 0,
					gravityzg double default 0,
					accelerationsensortotalg double default 0,
					accelerationsensorxaxisg double default 0,
					accelerationsensoryaxisg double default 0,
					accelerationsensorzaxisg double default 0,
					actualenginetorque double default 0,
					androiddevicebatterylevel double default 0,
					averagetripspeedwhilststoppedormovingkmh double default 0,
					coingkmaveragegkm double default 0,
					coingkminstantaneousgkm double default 0,
					distancetoemptyestimatedkm double default 0,
					distancetravelledwithmilcellitkm double default 0,
					enginecoolanttemperaturef double default 0,
					engineload double default 0,
					enginerpmrpm double default 0,
					fuelcosttripcost double default 0,
					fuelflowratehourlhr double default 0,
					fuelflowrateminuteccmin double default 0,
					fuelrailpressurekpa double default 0,
					fuelremainingcalculatedfromvehicleprofile double default 0,
					fuelusedtripl double default 0,
					fuelpressurekpa double default 0,
					gpsaccuracym double default 0,
					gpsaltitudem double default 0,
					gpsbearing double default 0,
					gpslatitude double default 0,
					gpslongitude double default 0,
					gpssatellites double default 0,
					gpsvsobdspeeddifferencekmh double default 0,
					horsepoweratthewheelshp double default 0,
					kilometersperlitreinstantkpl double default 0,
					kilometersperlitrelongtermaveragekpl double default 0,
					litresper100kilometerinstantl100km double default 0,
					litresper100kilometerlongtermaveragel100km double default 0,
					massairflowrategs double default 0,
					milespergalloninstantmpg double default 0,
					milespergallonlongtermaveragempg double default 0,
					speedgpskmh double default 0,
					speedobdkmh double default 0,
					torqueftlb double default 0,
					tripaveragekplkpl double default 0,
					tripaveragelitres100kml100km double default 0,
					tripaveragempgmpg double default 0,
					tripdistancekm double default 0,
					tripdistancestoredinvehicleprofilekm double default 0,
					triptimesincejourneystarts double default 0,
					triptimewhilstmovings double default 0,
					triptimewhilststationarys double default 0,
					turboboostvacuumgaugebar double default 0,
					voltageobdadapterv double default 0,
					volumetricefficiencycalculated double default 0,
					enginekwatthewheelskw double default 0,
					averagetripspeedwhilstmovingonlykmh double default 0,
					costpermilekminstantkm double default 0,
					costpermilekmtripkm double default 0,
					intakeairtemperaturef double default 0,
					intakemanifoldpressurekpa double default 0,
					key torqlogs_fk(tripid),
					foreign key(tripid) references torqfiles(id));

 """,
'createtrips': """
				create table if not exists torqtrips
				(
					id int primary key not null auto_increment,
					csvfilename varchar(255),
					csvhash varchar(255),
					distance double,
					fuelcost double,
					fuelused double,
					distancewhilstconnectedtoobd double,
					tripdate timestamp,
					profile varchar(255),
					time double,
					foreign key (id) references torqfiles (id),
					foreign key (id) references torqlogs (tripid)  );
					""",
'createdata': """
					create table if not exists torqdata (
					id int primary key not null auto_increment,
					tripdate timestamp,
					distance double default 0,
					fuelused double default 0,
					fuelcost double default 0,
					time double default 0,
					distancewhilstconnectedtoobd double default 0,
					minlongitude double default 0,
					maxlongitude double default 0,
					avglongitude double default 0,
					minlatitude double default 0,
					maxlatitude double default 0,
					avglatitude double default 0,
					mingpsspeedkmh double default 0,
					maxgpsspeedkmh double default 0,
					avggpsspeedkmh double default 0,
					minhorizontaldilutionofprecision double default 0,
					maxhorizontaldilutionofprecision double default 0,
					avghorizontaldilutionofprecision double default 0,
					minaltitudem double default 0,
					maxaltitudem double default 0,
					avgaltitudem double default 0,
					minbearing double default 0,
					maxbearing double default 0,
					avgbearing double default 0,
					mingravityxg double default 0,
					maxgravityxg double default 0,
					avggravityxg double default 0,
					mingravityyg double default 0,
					maxgravityyg double default 0,
					avggravityyg double default 0,
					mingravityzg double default 0,
					maxgravityzg double default 0,
					avggravityzg double default 0,
					minaccelerationsensortotalg double default 0,
					maxaccelerationsensortotalg double default 0,
					avgaccelerationsensortotalg double default 0,
					minaccelerationsensorxaxisg double default 0,
					maxaccelerationsensorxaxisg double default 0,
					avgaccelerationsensorxaxisg double default 0,
					minaccelerationsensoryaxisg double default 0,
					maxaccelerationsensoryaxisg double default 0,
					avgaccelerationsensoryaxisg double default 0,
					minaccelerationsensorzaxisg double default 0,
					maxaccelerationsensorzaxisg double default 0,
					avgaccelerationsensorzaxisg double default 0,
					minactualenginetorque double default 0,
					maxactualenginetorque double default 0,
					avgactualenginetorque double default 0,
					minandroiddevicebatterylevel double default 0,
					maxandroiddevicebatterylevel double default 0,
					avgandroiddevicebatterylevel double default 0,
					minaveragetripspeedwhilststoppedormovingkmh double default 0,
					maxaveragetripspeedwhilststoppedormovingkmh double default 0,
					avgaveragetripspeedwhilststoppedormovingkmh double default 0,
					mincoingkmaveragegkm double default 0,
					maxcoingkmaveragegkm double default 0,
					avgcoingkmaveragegkm double default 0,
					mincoingkminstantaneousgkm double default 0,
					maxcoingkminstantaneousgkm double default 0,
					avgcoingkminstantaneousgkm double default 0,
					mindistancetoemptyestimatedkm double default 0,
					maxdistancetoemptyestimatedkm double default 0,
					avgdistancetoemptyestimatedkm double default 0,
					mindistancetravelledwithmilcellitkm double default 0,
					maxdistancetravelledwithmilcellitkm double default 0,
					avgdistancetravelledwithmilcellitkm double default 0,
					minenginecoolanttemperaturef double default 0,
					maxenginecoolanttemperaturef double default 0,
					avgenginecoolanttemperaturef double default 0,
					minengineload double default 0,
					maxengineload double default 0,
					avgengineload double default 0,
					minenginerpmrpm double default 0,
					maxenginerpmrpm double default 0,
					avgenginerpmrpm double default 0,
					minfuelcosttripcost double default 0,
					maxfuelcosttripcost double default 0,
					avgfuelcosttripcost double default 0,
					minfuelflowratehourlhr double default 0,
					maxfuelflowratehourlhr double default 0,
					avgfuelflowratehourlhr double default 0,
					minfuelflowrateminuteccmin double default 0,
					maxfuelflowrateminuteccmin double default 0,
					avgfuelflowrateminuteccmin double default 0,
					minfuelrailpressurekpa double default 0,
					maxfuelrailpressurekpa double default 0,
					avgfuelrailpressurekpa double default 0,
					minfuelremainingcalculatedfromvehicleprofile double default 0,
					maxfuelremainingcalculatedfromvehicleprofile double default 0,
					avgfuelremainingcalculatedfromvehicleprofile double default 0,
					minfuelusedtripl double default 0,
					maxfuelusedtripl double default 0,
					avgfuelusedtripl double default 0,
					mingpsaccuracym double default 0,
					maxgpsaccuracym double default 0,
					avggpsaccuracym double default 0,
					mingpsaltitudem double default 0,
					maxgpsaltitudem double default 0,
					avggpsaltitudem double default 0,
					mingpsbearing double default 0,
					maxgpsbearing double default 0,
					avggpsbearing double default 0,
					mingpslatitude double default 0,
					maxgpslatitude double default 0,
					avggpslatitude double default 0,
					mingpslongitude double default 0,
					maxgpslongitude double default 0,
					avggpslongitude double default 0,
					mingpssatellites double default 0,
					maxgpssatellites double default 0,
					avggpssatellites double default 0,
					mingpsvsobdspeeddifferencekmh double default 0,
					maxgpsvsobdspeeddifferencekmh double default 0,
					avggpsvsobdspeeddifferencekmh double default 0,
					minhorsepoweratthewheelshp double default 0,
					maxhorsepoweratthewheelshp double default 0,
					avghorsepoweratthewheelshp double default 0,
					minkilometersperlitrelongtermaveragekpl double default 0,
					maxkilometersperlitrelongtermaveragekpl double default 0,
					avgkilometersperlitrelongtermaveragekpl double default 0,
					minlitresper100kilometerinstantl100km double default 0,
					maxlitresper100kilometerinstantl100km double default 0,
					avglitresper100kilometerinstantl100km double default 0,
					minlitresper100kilometerlongtermaveragel100km double default 0,
					maxlitresper100kilometerlongtermaveragel100km double default 0,
					avglitresper100kilometerlongtermaveragel100km double default 0,
					minmassairflowrategs double default 0,
					maxmassairflowrategs double default 0,
					avgmassairflowrategs double default 0,
					minmilespergalloninstantmpg double default 0,
					maxmilespergalloninstantmpg double default 0,
					avgmilespergalloninstantmpg double default 0,
					minmilespergallonlongtermaveragempg double default 0,
					maxmilespergallonlongtermaveragempg double default 0,
					avgmilespergallonlongtermaveragempg double default 0,
					maxspeedgpskmh double default 0,
					avgspeedgpskmh double default 0,
					maxspeedobdkmh double default 0,
					avgspeedobdkmh double default 0,
					mintorqueftlb double default 0,
					maxtorqueftlb double default 0,
					avgtorqueftlb double default 0,
					mintripaveragekplkpl double default 0,
					maxtripaveragekplkpl double default 0,
					avgtripaveragekplkpl double default 0,
					mintripaveragelitres100kml100km double default 0,
					maxtripaveragelitres100kml100km double default 0,
					avgtripaveragelitres100kml100km double default 0,
					mintripaveragempgmpg double default 0,
					maxtripaveragempgmpg double default 0,
					avgtripaveragempgmpg double default 0,
					mintripdistancekm double default 0,
					maxtripdistancekm double default 0,
					avgtripdistancekm double default 0,
					mintripdistancestoredinvehicleprofilekm double default 0,
					maxtripdistancestoredinvehicleprofilekm double default 0,
					avgtripdistancestoredinvehicleprofilekm double default 0,
					mintriptimesincejourneystarts double default 0,
					maxtriptimesincejourneystarts double default 0,
					avgtriptimesincejourneystarts double default 0,
					mintriptimewhilstmovings double default 0,
					maxtriptimewhilstmovings double default 0,
					avgtriptimewhilstmovings double default 0,
					mintriptimewhilststationarys double default 0,
					maxtriptimewhilststationarys double default 0,
					avgtriptimewhilststationarys double default 0,
					minturboboostvacuumgaugebar double default 0,
					maxturboboostvacuumgaugebar double default 0,
					avgturboboostvacuumgaugebar double default 0,
					minvoltageobdadapterv double default 0,
					maxvoltageobdadapterv double default 0,
					avgvoltageobdadapterv double default 0,
					minvolumetricefficiencycalculated double default 0,
					maxvolumetricefficiencycalculated double default 0,
					avgvolumetricefficiencycalculated double default 0,
					minenginekwatthewheelskw text collate utf8mb4_unicode_ci default 0,
					maxenginekwatthewheelskw text collate utf8mb4_unicode_ci default 0,
					avgenginekwatthewheelskw text collate utf8mb4_unicode_ci default 0,
					minaveragetripspeedwhilstmovingonlykmh text collate utf8mb4_unicode_ci default 0,
					maxaveragetripspeedwhilstmovingonlykmh text collate utf8mb4_unicode_ci default 0,
					avgaveragetripspeedwhilstmovingonlykmh text collate utf8mb4_unicode_ci default 0,
					mincostpermilekminstantkm text collate utf8mb4_unicode_ci default 0,
					maxcostpermilekminstantkm text collate utf8mb4_unicode_ci default 0,
					avgcostpermilekminstantkm text collate utf8mb4_unicode_ci default 0,
					mincostpermilekmtripkm text collate utf8mb4_unicode_ci default 0,
					maxcostpermilekmtripkm text collate utf8mb4_unicode_ci default 0,
					avgcostpermilekmtripkm text collate utf8mb4_unicode_ci default 0,
					minintakeairtemperaturef double default 0,
					maxintakeairtemperaturef double default 0,
					avgintakeairtemperaturef double default 0,
					minintakemanifoldpressurekpa double default 0,
					maxintakemanifoldpressurekpa double default 0,
					avgintakemanifoldpressurekpa double default 0,
					key torqdata_fk (id),
					foreign key (id) references torqlogs (tripid),
					foreign key (id) references torqfiles (id));

	  """
}

sqlite_cmds = {
'createfiles' : """
	create table if not exists torqfiles
	(
	id           integer primary key,
	csvfilename  varchar(255),
	csvhash      varchar(255),
	csvfilefixed varchar(255),
	fixedhash    varchar(255)
	);
""",
'createtrips' : """
	create table if not exists torqtrips	(
	id int integer primary key,
	csvfilename varchar(255),
	csvhash varchar(255),
	distance int,
	fuelcost int,
	fuelused int,
	distancewhilstconnectedtoobd int,
	tripdate datetime,
	profile varchar(255),
	time int
	);
	""",
'createlogs' : """
	create table if not exists torqlogs
	(
		id integer primary key,
		tripid int ,
		gpstime timestamp default current_timestamp,
		devicetime timestamp default current_timestamp,
		longitude float default 0,
		latitude float default 0,
		gpsspeedkmh float default 0,
		horizontaldilutionofprecision float default 0,
		altitudem float default 0,
		bearing float default 0,
		gravityxg float default 0,
		gravityyg float default 0,
		gravityzg float default 0,
		accelerationsensortotalg float default 0,
		accelerationsensorxaxisg float default 0,
		accelerationsensoryaxisg float default 0,
		accelerationsensorzaxisg float default 0,
		actualenginetorque float default 0,
		androiddevicebatterylevel float default 0,
		averagetripspeedwhilststoppedormovingkmh float default 0,
		coingkmaveragegkm float default 0,
		coingkminstantaneousgkm float default 0,
		distancetoemptyestimatedkm float default 0,
		distancetravelledwithmilcellitkm float default 0,
		enginecoolanttemperaturef float default 0,
		engineload float default 0,
		enginerpmrpm float default 0,
		fuelcosttripcost float default 0,
		fuelflowratehourlhr float default 0,
		fuelflowrateminuteccmin float default 0,
		fuelrailpressurekpa float default 0,
		fuelremainingcalculatedfromvehicleprofile float default 0,
		fuelusedtripl float default 0,
		gpsaccuracym float default 0,
		gpsaltitudem float default 0,
		gpsbearing float default 0,
		gpslatitude float default 0,
		gpslongitude float default 0,
		gpssatellites float default 0,
		gpsvsobdspeeddifferencekmh float default 0,
		horsepoweratthewheelshp float default 0,
		floatakeairtemperaturef float default 0,
		floatakemanifoldpressurekpa float default 0,
		kilometersperlitreinstantkpl float default 0,
		kilometersperlitrelongtermaveragekpl float default 0,
		litresper100kilometerinstantl100km float default 0,
		litresper100kilometerlongtermaveragel100km float default 0,
		massairflowrategs float default 0,
		milespergalloninstantmpg float default 0,
		milespergallonlongtermaveragempg float default 0,
		speedgpskmh float default 0,
		speedobdkmh float default 0,
		torqueftlb float default 0,
		tripaveragekplkpl float default 0,
		tripaveragelitres100kml100km float default 0,
		tripaveragempgmpg float default 0,
		tripdistancekm float default 0,
		tripdistancestoredinvehicleprofilekm float default 0,
		triptimesincejourneystarts float default 0,
		triptimewhilstmovings float default 0,
		triptimewhilststationarys float default 0,
		turboboostvacuumgaugebar float default 0,
		voltageobdadapterv float default 0,
		volumetricefficiencycalculated float default 0,
		enginekwatthewheelskw float default 0,
		averagetripspeedwhilstmovingonlykmh float default 0,
		costpermilekminstantkm float default 0,
		costpermilekmtripkm float default 0,
		intakeairtemperaturef float default 0,
		intakemanifoldpressurekpa float default 0
	);
""",
'createdata': """
		create table if not exists torqdata (
		id int primary key not null,
		tripid int,
		tripdate datetime default 0,
		distance double default 0,
		fuelused double default 0,
		fuelcost double default 0,
		time double default 0,
		distancewhilstconnectedtoobd double default 0,
		minlongitude double default 0,
		maxlongitude double default 0,
		avglongitude double default 0,
		minlatitude double default 0,
		maxlatitude double default 0,
		avglatitude double default 0,
		mingpsspeedkmh double default 0,
		maxgpsspeedkmh double default 0,
		avggpsspeedkmh double default 0,
		minhorizontaldilutionofprecision double default 0,
		maxhorizontaldilutionofprecision double default 0,
		avghorizontaldilutionofprecision double default 0,
		minaltitudem double default 0,
		maxaltitudem double default 0,
		avgaltitudem double default 0,
		minbearing double default 0,
		maxbearing double default 0,
		avgbearing double default 0,
		mingravityxg double default 0,
		maxgravityxg double default 0,
		avggravityxg double default 0,
		mingravityyg double default 0,
		maxgravityyg double default 0,
		avggravityyg double default 0,
		mingravityzg double default 0,
		maxgravityzg double default 0,
		avggravityzg double default 0,
		minaccelerationsensortotalg double default 0,
		maxaccelerationsensortotalg double default 0,
		avgaccelerationsensortotalg double default 0,
		minaccelerationsensorxaxisg double default 0,
		maxaccelerationsensorxaxisg double default 0,
		avgaccelerationsensorxaxisg double default 0,
		minaccelerationsensoryaxisg double default 0,
		maxaccelerationsensoryaxisg double default 0,
		avgaccelerationsensoryaxisg double default 0,
		minaccelerationsensorzaxisg double default 0,
		maxaccelerationsensorzaxisg double default 0,
		avgaccelerationsensorzaxisg double default 0,
		minactualenginetorque double default 0,
		maxactualenginetorque double default 0,
		avgactualenginetorque double default 0,
		minandroiddevicebatterylevel double default 0,
		maxandroiddevicebatterylevel double default 0,
		avgandroiddevicebatterylevel double default 0,
		minaveragetripspeedwhilststoppedormovingkmh double default 0,
		maxaveragetripspeedwhilststoppedormovingkmh double default 0,
		avgaveragetripspeedwhilststoppedormovingkmh double default 0,
		mincoingkmaveragegkm double default 0,
		maxcoingkmaveragegkm double default 0,
		avgcoingkmaveragegkm double default 0,
		mincoingkminstantaneousgkm double default 0,
		maxcoingkminstantaneousgkm double default 0,
		avgcoingkminstantaneousgkm double default 0,
		mindistancetoemptyestimatedkm double default 0,
		maxdistancetoemptyestimatedkm double default 0,
		avgdistancetoemptyestimatedkm double default 0,
		mindistancetravelledwithmilcellitkm double default 0,
		maxdistancetravelledwithmilcellitkm double default 0,
		avgdistancetravelledwithmilcellitkm double default 0,
		minenginecoolanttemperaturef double default 0,
		maxenginecoolanttemperaturef double default 0,
		avgenginecoolanttemperaturef double default 0,
		minengineload double default 0,
		maxengineload double default 0,
		avgengineload double default 0,
		minenginerpmrpm double default 0,
		maxenginerpmrpm double default 0,
		avgenginerpmrpm double default 0,
		minfuelcosttripcost double default 0,
		maxfuelcosttripcost double default 0,
		avgfuelcosttripcost double default 0,
		minfuelflowratehourlhr double default 0,
		maxfuelflowratehourlhr double default 0,
		avgfuelflowratehourlhr double default 0,
		minfuelflowrateminuteccmin double default 0,
		maxfuelflowrateminuteccmin double default 0,
		avgfuelflowrateminuteccmin double default 0,
		minfuelrailpressurekpa double default 0,
		maxfuelrailpressurekpa double default 0,
		avgfuelrailpressurekpa double default 0,
		minfuelremainingcalculatedfromvehicleprofile double default 0,
		maxfuelremainingcalculatedfromvehicleprofile double default 0,
		avgfuelremainingcalculatedfromvehicleprofile double default 0,
		minfuelusedtripl double default 0,
		maxfuelusedtripl double default 0,
		avgfuelusedtripl double default 0,
		mingpsaccuracym double default 0,
		maxgpsaccuracym double default 0,
		avggpsaccuracym double default 0,
		mingpsaltitudem double default 0,
		maxgpsaltitudem double default 0,
		avggpsaltitudem double default 0,
		mingpsbearing double default 0,
		maxgpsbearing double default 0,
		avggpsbearing double default 0,
		mingpslatitude double default 0,
		maxgpslatitude double default 0,
		avggpslatitude double default 0,
		mingpslongitude double default 0,
		maxgpslongitude double default 0,
		avggpslongitude double default 0,
		mingpssatellites double default 0,
		maxgpssatellites double default 0,
		avggpssatellites double default 0,
		mingpsvsobdspeeddifferencekmh double default 0,
		maxgpsvsobdspeeddifferencekmh double default 0,
		avggpsvsobdspeeddifferencekmh double default 0,
		minhorsepoweratthewheelshp double default 0,
		maxhorsepoweratthewheelshp double default 0,
		avghorsepoweratthewheelshp double default 0,
		minkilometersperlitrelongtermaveragekpl double default 0,
		maxkilometersperlitrelongtermaveragekpl double default 0,
		avgkilometersperlitrelongtermaveragekpl double default 0,
		minlitresper100kilometerinstantl100km double default 0,
		maxlitresper100kilometerinstantl100km double default 0,
		avglitresper100kilometerinstantl100km double default 0,
		minlitresper100kilometerlongtermaveragel100km double default 0,
		maxlitresper100kilometerlongtermaveragel100km double default 0,
		avglitresper100kilometerlongtermaveragel100km double default 0,
		minmassairflowrategs double default 0,
		maxmassairflowrategs double default 0,
		avgmassairflowrategs double default 0,
		minmilespergalloninstantmpg double default 0,
		maxmilespergalloninstantmpg double default 0,
		avgmilespergalloninstantmpg double default 0,
		minmilespergallonlongtermaveragempg double default 0,
		maxmilespergallonlongtermaveragempg double default 0,
		avgmilespergallonlongtermaveragempg double default 0,
		maxspeedgpskmh double default 0,
		avgspeedgpskmh double default 0,
		maxspeedobdkmh double default 0,
		avgspeedobdkmh double default 0,
		mintorqueftlb double default 0,
		maxtorqueftlb double default 0,
		avgtorqueftlb double default 0,
		mintripaveragekplkpl double default 0,
		maxtripaveragekplkpl double default 0,
		avgtripaveragekplkpl double default 0,
		mintripaveragelitres100kml100km double default 0,
		maxtripaveragelitres100kml100km double default 0,
		avgtripaveragelitres100kml100km double default 0,
		mintripaveragempgmpg double default 0,
		maxtripaveragempgmpg double default 0,
		avgtripaveragempgmpg double default 0,
		mintripdistancekm double default 0,
		maxtripdistancekm double default 0,
		avgtripdistancekm double default 0,
		mintripdistancestoredinvehicleprofilekm double default 0,
		maxtripdistancestoredinvehicleprofilekm double default 0,
		avgtripdistancestoredinvehicleprofilekm double default 0,
		mintriptimesincejourneystarts double default 0,
		maxtriptimesincejourneystarts double default 0,
		avgtriptimesincejourneystarts double default 0,
		mintriptimewhilstmovings double default 0,
		maxtriptimewhilstmovings double default 0,
		avgtriptimewhilstmovings double default 0,
		mintriptimewhilststationarys double default 0,
		maxtriptimewhilststationarys double default 0,
		avgtriptimewhilststationarys double default 0,
		minturboboostvacuumgaugebar double default 0,
		maxturboboostvacuumgaugebar double default 0,
		avgturboboostvacuumgaugebar double default 0,
		minvoltageobdadapterv double default 0,
		maxvoltageobdadapterv double default 0,
		avgvoltageobdadapterv double default 0,
		minvolumetricefficiencycalculated double default 0,
		maxvolumetricefficiencycalculated double default 0,
		avgvolumetricefficiencycalculated double default 0,
		minenginekwatthewheelskw double default 0,
		maxenginekwatthewheelskw double default 0,
		avgenginekwatthewheelskw double default 0,
		minaveragetripspeedwhilstmovingonlykmh double default 0,
		maxaveragetripspeedwhilstmovingonlykmh double default 0,
		avgaveragetripspeedwhilstmovingonlykmh double default 0,
		mincostpermilekminstantkm double default 0,
		maxcostpermilekminstantkm double default 0,
		avgcostpermilekminstantkm double default 0,
		mincostpermilekmtripkm double default 0,
		maxcostpermilekmtripkm double default 0,
		avgcostpermilekmtripkm double default 0,
		minintakeairtemperaturef double default 0,
		maxintakeairtemperaturef double default 0,
		avgintakeairtemperaturef double default 0,
		minintakemanifoldpressurekpa double default 0,
		maxintakemanifoldpressurekpa double default 0,
		avgintakemanifoldpressurekpa double default 0,
		key torqdata_fk (tripid),
		constraint torqdata_fk foreign key (tripid) references torqtrips (id)
		)
	  """}


postgresql_cmds= {
	'createfiles' : """
 create table if not exists torqfiles
(
id int generated always as identity PRIMARY KEY,
csvfilename  varchar(255),
csvhash varchar(255),
csvfilefixed varchar(255),
fixedhash varchar(255)
);
""",
'createlogs' : """
create table if not exists torqlogs
(
			id int generated always as identity PRIMARY KEY,
			tripid int not null,
			csvhash varchar(255) default 0,
			gpstime timestamp default current_timestamp,
			devicetime timestamp default current_timestamp,
			longitude double precision,
			latitude double precision,
			gpsspeedkmh double precision,
			horizontaldilutionofprecision double precision,
			altitudem double precision,
			bearing double precision,
			gravityxg double precision,
			gravityyg double precision,
			gravityzg double precision,
			accelerationsensortotalg double precision,
			accelerationsensorxaxisg double precision,
			accelerationsensoryaxisg double precision,
			accelerationsensorzaxisg double precision,
			actualenginetorque double precision,
			androiddevicebatterylevel                double precision,
			averagetripspeedwhilststoppedormovingkmh double precision,
			coingkmaveragegkm double precision,
			coingkminstantaneousgkm                  double precision,
			distancetoemptyestimatedkm               double precision,
			distancetravelledwithmilcellitkm double precision,
			enginecoolanttemperaturef double precision,
			engineload double precision,
			enginerpmrpm double precision,
			fuelcosttripcost        double precision,
			fuelflowratehourlhr     double precision,
			fuelflowrateminuteccmin double precision,
			fuelrailpressurekpa double precision,
			fuelremainingcalculatedfromvehicleprofile double precision,
			fuelusedtripl double precision,
			fuelpressurekpa double precision,
			gpsaccuracym double precision,
			gpsaltitudem double precision,
			gpsbearing double precision,
			gpslatitude double precision,
			gpslongitude double precision,
			gpssatellites double precision,
			gpsvsobdspeeddifferencekmh                double precision,
			horsepoweratthewheelshp double precision,
			intakeairtemperaturef double precision,
			intakemanifoldpressurekpa double precision,
			kilometersperlitreinstantkpl               double precision,
			kilometersperlitrelongtermaveragekpl       double precision,
			litresper100kilometerinstantl100km         double precision,
			litresper100kilometerlongtermaveragel100km double precision,
			massairflowrategs double precision,
			milespergalloninstantmpg         double precision,
			milespergallonlongtermaveragempg double precision,
			speedgpskmh double precision,
			speedobdkmh double precision,
			torqueftlb double precision,
			tripaveragekplkpl double precision,
			tripaveragelitres100kml100km         double precision,
			tripaveragempgmpg double precision,
			tripdistancekm double precision,
			tripdistancestoredinvehicleprofilekm double precision,
			triptimesincejourneystarts           double precision,
			triptimewhilstmovings                double precision,
			triptimewhilststationarys            double precision,
			turboboostvacuumgaugebar double precision,
			voltageobdadapterv                  double precision,
			volumetricefficiencycalculated      double precision,
			enginekwatthewheelskw               double precision,
			averagetripspeedwhilstmovingonlykmh double precision,
			costpermilekminstantkm double precision,
			costpermilekmtripkm double precision,
			foreign key(tripid) references torqfiles(id)
);
""", # 	foreign key (id) references torqlogs (tripid)
'createtrips': """
create table if not exists torqtrips
(
	id int generated always as identity PRIMARY KEY,
	csvfilename varchar(255),
	csvhash varchar(255),
	distance double precision,
	fuelcost double precision,
	fuelused double precision,
	distancewhilstconnectedtoobd double precision,
	tripdate varchar(255),
	profile  varchar(255),
	time double precision,
	foreign key (id) references torqfiles (id)
);
""",
'createdata': """
create table if not exists torqdata (
id int generated always as identity PRIMARY KEY,
tripdate timestamp,
distance double precision,
fuelused double precision,
fuelcost double precision,
time double precision,
distancewhilstconnectedtoobd double precision,
minlongitude double precision,
maxlongitude double precision,
avglongitude double precision,
minlatitude double precision,
maxlatitude double precision,
avglatitude double precision,
mingpsspeedkmh double precision,
maxgpsspeedkmh double precision,
avggpsspeedkmh double precision,
minhorizontaldilutionofprecision double precision,
maxhorizontaldilutionofprecision double precision,
avghorizontaldilutionofprecision double precision,
minaltitudem double precision,
maxaltitudem double precision,
avgaltitudem double precision,
minbearing double precision,
maxbearing double precision,
avgbearing double precision,
mingravityxg double precision,
maxgravityxg double precision,
avggravityxg double precision,
mingravityyg double precision,
maxgravityyg double precision,
avggravityyg double precision,
mingravityzg double precision,
maxgravityzg double precision,
avggravityzg double precision,
minaccelerationsensortotalg double precision,
maxaccelerationsensortotalg double precision,
avgaccelerationsensortotalg double precision,
minaccelerationsensorxaxisg double precision,
maxaccelerationsensorxaxisg double precision,
avgaccelerationsensorxaxisg double precision,
minaccelerationsensoryaxisg double precision,
maxaccelerationsensoryaxisg double precision,
avgaccelerationsensoryaxisg double precision,
minaccelerationsensorzaxisg double precision,
maxaccelerationsensorzaxisg double precision,
avgaccelerationsensorzaxisg double precision,
minactualenginetorque double precision,
maxactualenginetorque double precision,
avgactualenginetorque double precision,
minandroiddevicebatterylevel double precision,
maxandroiddevicebatterylevel double precision,
avgandroiddevicebatterylevel double precision,
minaveragetripspeedwhilststoppedormovingkmh double precision,
maxaveragetripspeedwhilststoppedormovingkmh double precision,
avgaveragetripspeedwhilststoppedormovingkmh double precision,
mincoingkmaveragegkm double precision,
maxcoingkmaveragegkm double precision,
avgcoingkmaveragegkm double precision,
mincoingkminstantaneousgkm double precision,
maxcoingkminstantaneousgkm double precision,
avgcoingkminstantaneousgkm double precision,
mindistancetoemptyestimatedkm double precision,
maxdistancetoemptyestimatedkm double precision,
avgdistancetoemptyestimatedkm double precision,
mindistancetravelledwithmilcellitkm double precision,
maxdistancetravelledwithmilcellitkm double precision,
avgdistancetravelledwithmilcellitkm double precision,
minenginecoolanttemperaturef double precision,
maxenginecoolanttemperaturef double precision,
avgenginecoolanttemperaturef double precision,
minengineload double precision,
maxengineload double precision,
avgengineload double precision,
minenginerpmrpm double precision,
maxenginerpmrpm double precision,
avgenginerpmrpm double precision,
minfuelcosttripcost double precision,
maxfuelcosttripcost double precision,
avgfuelcosttripcost double precision,
minfuelflowratehourlhr double precision,
maxfuelflowratehourlhr double precision,
avgfuelflowratehourlhr double precision,
minfuelflowrateminuteccmin double precision,
maxfuelflowrateminuteccmin double precision,
avgfuelflowrateminuteccmin double precision,
minfuelrailpressurekpa double precision,
maxfuelrailpressurekpa double precision,
avgfuelrailpressurekpa double precision,
minfuelremainingcalculatedfromvehicleprofile double precision,
maxfuelremainingcalculatedfromvehicleprofile double precision,
avgfuelremainingcalculatedfromvehicleprofile double precision,
minfuelusedtripl double precision,
maxfuelusedtripl double precision,
avgfuelusedtripl double precision,
mingpsaccuracym double precision,
maxgpsaccuracym double precision,
avggpsaccuracym double precision,
mingpsaltitudem double precision,
maxgpsaltitudem double precision,
avggpsaltitudem double precision,
mingpsbearing double precision,
maxgpsbearing double precision,
avggpsbearing double precision,
mingpslatitude double precision,
maxgpslatitude double precision,
avggpslatitude double precision,
mingpslongitude double precision,
maxgpslongitude double precision,
avggpslongitude double precision,
mingpssatellites double precision,
maxgpssatellites double precision,
avggpssatellites double precision,
mingpsvsobdspeeddifferencekmh double precision,
maxgpsvsobdspeeddifferencekmh double precision,
avggpsvsobdspeeddifferencekmh double precision,
minhorsepoweratthewheelshp double precision,
maxhorsepoweratthewheelshp double precision,
avghorsepoweratthewheelshp double precision,
minkilometersperlitrelongtermaveragekpl double precision,
maxkilometersperlitrelongtermaveragekpl double precision,
avgkilometersperlitrelongtermaveragekpl double precision,
minlitresper100kilometerinstantl100km double precision,
maxlitresper100kilometerinstantl100km double precision,
avglitresper100kilometerinstantl100km double precision,
minlitresper100kilometerlongtermaveragel100km double precision,
maxlitresper100kilometerlongtermaveragel100km double precision,
avglitresper100kilometerlongtermaveragel100km double precision,
minmassairflowrategs double precision,
maxmassairflowrategs double precision,
avgmassairflowrategs double precision,
minmilespergalloninstantmpg double precision,
maxmilespergalloninstantmpg double precision,
avgmilespergalloninstantmpg double precision,
minmilespergallonlongtermaveragempg double precision,
maxmilespergallonlongtermaveragempg double precision,
avgmilespergallonlongtermaveragempg double precision,
maxspeedgpskmh double precision,
avgspeedgpskmh double precision,
maxspeedobdkmh double precision,
avgspeedobdkmh double precision,
mintorqueftlb double precision,
maxtorqueftlb double precision,
avgtorqueftlb double precision,
mintripaveragekplkpl double precision,
maxtripaveragekplkpl double precision,
avgtripaveragekplkpl double precision,
mintripaveragelitres100kml100km double precision,
maxtripaveragelitres100kml100km double precision,
avgtripaveragelitres100kml100km double precision,
mintripaveragempgmpg double precision,
maxtripaveragempgmpg double precision,
avgtripaveragempgmpg double precision,
mintripdistancekm double precision,
maxtripdistancekm double precision,
avgtripdistancekm double precision,
mintripdistancestoredinvehicleprofilekm double precision,
maxtripdistancestoredinvehicleprofilekm double precision,
avgtripdistancestoredinvehicleprofilekm double precision,
mintriptimesincejourneystarts double precision,
maxtriptimesincejourneystarts double precision,
avgtriptimesincejourneystarts double precision,
mintriptimewhilstmovings double precision,
maxtriptimewhilstmovings double precision,
avgtriptimewhilstmovings double precision,
mintriptimewhilststationarys double precision,
maxtriptimewhilststationarys double precision,
avgtriptimewhilststationarys double precision,
minturboboostvacuumgaugebar double precision,
maxturboboostvacuumgaugebar double precision,
avgturboboostvacuumgaugebar double precision,
minvoltageobdadapterv double precision,
maxvoltageobdadapterv double precision,
avgvoltageobdadapterv double precision,
minvolumetricefficiencycalculated double precision,
maxvolumetricefficiencycalculated double precision,
avgvolumetricefficiencycalculated double precision,
minenginekwatthewheelskw double precision default 0,
maxenginekwatthewheelskw double precision default 0,
avgenginekwatthewheelskw double precision default 0,
minaveragetripspeedwhilstmovingonlykmh double precision default 0,
maxaveragetripspeedwhilstmovingonlykmh double precision default 0,
avgaveragetripspeedwhilstmovingonlykmh double precision default 0,
mincostpermilekminstantkm double precision default 0,
maxcostpermilekminstantkm double precision default 0,
avgcostpermilekminstantkm double precision default 0,
mincostpermilekmtripkm double precision default 0,
maxcostpermilekmtripkm double precision default 0,
avgcostpermilekmtripkm double precision default 0,
minintakeairtemperaturef double precision,
maxintakeairtemperaturef double precision,
avgintakeairtemperaturef double precision,
minintakemanifoldpressurekpa double precision,
maxintakemanifoldpressurekpa double precision,
avgintakemanifoldpressurekpa double precision,
foreign key (id) references torqfiles (id));

	  """
}

sqlcmds = {
	'mysql': mysql_cmds,
	'sqlite' : sqlite_cmds,
	'postgresql' : postgresql_cmds
	}